accounts/urls.py
from django.urls import path

from . import views


app_name = 'accounts'
urlpatterns = [
    path('', views.minha_conta, name='minha_conta'),
    path('registro/', views.register, name='register'),
    path('atualizaUsuario/', views.atualiza_user, name='atualiza_user'),
    path('atualizaSenha/', views.atualiza_password, name='atualiza_senha')
]

djangoecommerce/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views

from core import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('login', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout', auth_views.LogoutView.as_view(next_page='/'), name='logout'),
    path('', views.index, name='index'),
    path('sobre/', views.sobre, name='sobre'),
    path('contato', views.contato, name='contato'),
    path('catalogo/', include('catalogo.urls', namespace='catalogo')),
    path('conta/', include('accounts.urls', namespace='accounts')),
    path('compras/', include('checkout.urls', namespace='checkout'))

]

accounts/models.py
import re

from django.db import models
from django.core import validators
from django.contrib.auth.models import AbstractBaseUser, UserManager, PermissionsMixin, BaseUserManager


class User(AbstractBaseUser, PermissionsMixin):

    username = models.CharField(
        'Apelido / Usuário', max_length=30, unique=True, validators=[
            validators.RegexValidator(
                re.compile('^[\w.@+-]+$'),
                'Informe um usuário válido. '
                'Este valor deve ter apenas letras, numeros '
                'e os caracteres: @ . + - _ .'
                , 'invalid'
            )
        ], help_text='Um nome curto que será usado para identificá-lo'
    )
    nome = models.CharField('Nome', max_length=100)
    email = models.EmailField('E-mail', unique=True)
    is_staff = models.BooleanField('Equipe', default=False)
    is_active = models.BooleanField('Ativo', default=True)
    date_joined = models.DateTimeField('Data de Entrada', auto_now_add=True)

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    objects = UserManager()

    class Meta:
        verbose_name = 'Usuário'
        verbose_name_plural = 'Usuários'

    def __str__(self):
        return self.nome or self.username

    def get_full_name(self):
        return str(self)

    def get_short_name(self):
        return str(self).split(' ')[0]

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, ReadOnlyPasswordHashField

from .models import User


class UserAdminCreationForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('email', 'username')


class UserAdminChangeForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ('email', 'nome', 'username', 'is_active', 'is_staff')

accounts/views.py
from django.views.generic import CreateView, TemplateView, UpdateView, FormView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import PasswordChangeForm

from .models import User
from .forms import UserAdminCreationForm


class MinhaContaView(LoginRequiredMixin, TemplateView):

    template_name = 'accounts/minha_conta.html'


class RegisterView(CreateView):

    model = User
    template_name = 'accounts/nova_conta.html'
    form_class = UserAdminCreationForm
    success_url = reverse_lazy('index')


class AtualizaUserView(LoginRequiredMixin, UpdateView):

    model = User
    template_name = 'accounts/update_conta.html'
    fields = ['nome', 'email']
    success_url = reverse_lazy('accounts:minha_conta')

    def get_object(self, queryset=None):
        return self.request.user


class AtualizaSenhaView(LoginRequiredMixin, FormView):

    template_name = 'accounts/update_password.html'
    success_url = reverse_lazy('accounts:minha_conta')
    form_class = PasswordChangeForm

    def get_form_kwargs(self):
        kwargs = super(AtualizaSenhaView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        form.save()
        return super(AtualizaSenhaView, self).form_valid(form)


minha_conta = MinhaContaView.as_view()
register = RegisterView.as_view()
atualiza_user = AtualizaUserView.as_view()
atualiza_password = AtualizaSenhaView.as_view()

accounts/templates/accounts/minha_conta.html
{% extends "base.html" %}

{% block title %}Minha conta | {{ block.super }}{% endblock %}

{% block container %}
    <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="#">Home</a></li>
                <li class="breadcrumb-item active" aria-current="page">Minha conta</li>
            </ol>
    </nav>

    <div class="row">

      <div class="col-lg-3">

        <div class="list-group">
            <a href="#" class="list-group-item active">Minha Conta</a>
            <a href="{% url 'accounts:atualiza_user' %}" class="list-group-item">Alterar Dados</a>
            <a href="{% url 'accounts:atualiza_senha' %}" class="list-group-item">Alterar Senha</a>
        </div>

      </div>
      <!-- /.col-lg-3 -->

      <div class="col-lg-9">
          {% block accounts_container %}
                <h1 class="my-4">Django</h1>
          {% endblock %}

        <!-- /.row -->

      </div>
      <!-- /.col-lg-9 -->

    </div>
    <!-- /.row -->

{% endblock %}

accounts/templates/accounts/nova_conta.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block title %}
    Nova conta | {{ block.super }}
{% endblock %}

{% block container %}
    <div class="row">
      <div class="col-lg-10 col-xl-9 mx-auto">
        <div class="card card-signin flex-row my-5">
        {% for error in form.non_field_errors %}
                <div class="alert-danger">
                {{ error }}
                </div>
            {% endfor %}
          <div class="card-img-left d-none d-md-flex">
             <!-- Background image for card set in CSS! -->
          </div>
          <div class="card-body">
            <h5 class="card-title text-center">Nova conta</h5>
            <form class="form-signin" method="post">
                {% csrf_token %}
                {% for field in form %}
                    <div class="form-label-group{% if field.errors %} is-invalid {% endif %}">
                    {% render_field field class="form-control" %}
                    <label for="{{ field.auto_id }}">{{ field.label }}</label>
                    {% for error in field.errors %}
                        <span class="invalid-feedback">{{ error }}</span>
                    {% endfor %}
                    </div>
                {% endfor %}
              <button class="btn btn-lg btn-primary btn-block text-uppercase" type="submit">Registrar-se</button>
              <a class="d-block text-center mt-2 small" href="#">Entrar</a>
              <hr class="my-4">
            </form>
          </div>
        </div>
      </div>
    </div>
{% endblock %}

accounts/templates/accounts/update_conta.html
{% extends "accounts/minha_conta.html" %}

{% load widget_tweaks %}

{% block title %}
    Alterar dados | {{ block.super }}
{% endblock %}

{% block accounts_container %}
    <h2>Alterar dados</h2>
        <form class="form-horizontal" action="" method="post">
            {% csrf_token %}
            {% for field in form %}
            <div class="form-group{% if field.errors %} has-error{% endif %}">
            <label for="{{ field.auto_id }}" class="col-md-3 control-label">{{ field.name }}</label>
            <div class="col-md-9">
                {%  render_field field class='form-control' %}
                {% for error in field.errors %}
                    <span class="invalid-feedback">{{ error }}</span>
                {% endfor %}
            </div>
            </div>
            {% endfor %}
            <button type="submit" class="btn btn-primary">Salvar</button>
        </form>
{% endblock %}

accounts/templates/accounts/update_password.html
{% extends "accounts/minha_conta.html" %}

{% load widget_tweaks %}

{% block title %}
    Alterar senha | {{ block.super }}
{% endblock %}

{% block accounts_container %}
    <h2>Alterar senha</h2>
        <form class="form-horizontal" action="" method="post">
            {% csrf_token %}
            {% for field in form %}
            <div class="form-group{% if field.errors %} has-error{% endif %}">
            <label for="{{ field.auto_id }}" class="col-md-3 control-label">{{ field.name }}</label>
            <div class="col-md-9">
                {%  render_field field class='form-control' %}
                {% for error in field.errors %}
                    <span class="invalid-feedback">{{ error }}</span>
                {% endfor %}
            </div>
            </div>
            {% endfor %}
            <button type="submit" class="btn btn-primary">Salvar</button>
        </form>
{% endblock %}