accounts/urls.py
from django.urls import path

from . import views


app_name = 'accounts'
urlpatterns = [
    path('', views.minha_conta, name='minha_conta'),
    path('registro/', views.register, name='register'),
    path('atualizaUsuario/', views.atualiza_user, name='atualiza_user'),
    path('atualizaSenha/', views.atualiza_password, name='atualiza_senha')
]

catalogo/urls.py
from django.urls import path

from . import views


app_name = 'catalogo'
urlpatterns = [
    path('', views.servicos, name='servicos'),
    path('<slug:slug>/', views.categoria, name='categoria'),
    path('produtos/<slug:slug>/', views.servico, name='servico'),

]

djangoecommerce/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views

from core import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('login', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout', auth_views.LogoutView.as_view(next_page='/'), name='logout'),
    path('', views.index, name='index'),
    path('sobre/', views.sobre, name='sobre'),
    path('contato', views.contato, name='contato'),
    path('catalogo/', include('catalogo.urls', namespace='catalogo')),
    path('conta/', include('accounts.urls', namespace='accounts')),
    path('compras/', include('checkout.urls', namespace='checkout'))

]

core/models.py
from django.db import models

# Create your models here.

core/forms.py
from django import forms
from django.core.mail import send_mail
from django.conf import settings


class ContatoForm(forms.Form):

    nome = forms.CharField(label='Nome')
    email = forms.EmailField(label='E-mail')
    mensagem = forms.CharField(label='Mensagem', widget=forms.Textarea())

    def send_email(self):
        nome = self.cleaned_data['nome']
        email = self.cleaned_data['email']
        mensagem = self.cleaned_data['mensagem']
        mensagem = 'Nome: {0}\nEmail:{1}\n{2}'.format(nome, email, mensagem)
        send_mail('Contato Django Ecommerce', mensagem, settings.DEFAULT_FROM_EMAIL, [settings.DEFAULT_FROM_EMAIL])

core/views.py
from django.shortcuts import render
from django.views.generic import ListView
from django.contrib.auth import get_user_model
from django.contrib import messages

from .forms import ContatoForm

from catalogo.models import Categoria

User = get_user_model()


class IndexView(ListView):

    model = Categoria
    template_name = 'index.html'
    context_object_name = 'categorias'


index = IndexView.as_view()


def sobre(request):
    return render(request, 'sobre.html')


def contato(request):
    success = False
    request.session['teste'] = 'teste'
    print(request.session['teste'])
    form = ContatoForm(request.POST or None)
    if form.is_valid():
        form.send_email()
        success = True
    elif request.method == 'POST':
        messages.error(request, 'Formulario invalido')
    context = {
        'form': form,
        'success': success
    }
    return render(request, 'contato.html', context)

core/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>{% block title %}Django E-commerce{% endblock %}</title>

  <!-- Bootstrap core CSS -->
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{% static 'css/shop-homepage.css' %}" rel="stylesheet">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="{% url 'index' %}">Django E-Commerce</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="nav navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'index' %}">Inicio
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'sobre' %}">Sobre</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'catalogo:servicos' %}">Serviços</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'contato' %}">Contato</a>
          </li>
        </ul>
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
            {% if user.is_authenticated %}
                <li class="m-0 text-center text-white">Olá {{ user }}</li>
                <a class="nav-link" href="{% url 'logout' %}">Sair</a>
            {% else %}
                <a class="nav-link" href="{% url 'login' %}">Minha conta</a>
                <li> <a class="nav-link" href="{% url 'accounts:register' %}">Registrar-se</a></li>
            {% endif %}
            </li>
            </ul>
      </div>
    </div>
  </nav>

  <!-- Page Content -->
  <div class="container">
        {% block messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">
                    {{ message }}
                </div>
            {% endfor %}
        {% endblock %}
        {% block container %}{% endblock %}
  </div>
  <!-- /.container -->

  <!-- Footer -->
  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Seu Website 2019</p>
    </div>
    <!-- /.container -->
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

</body>

</html>

core/templates/contato.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block title %}
    Contato | {{ block.super }}
{% endblock %}

{% block container %}
    <div class="row">
        <div class="col-lg-8 col-md-6 mb-4">
    <h1 class="my-4">Fale conosco</h1>
        {% if succes %}
            <div class="alert alert-success">
            Mensagem enviada para email.
            </div>
        {% endif %}
    <form action="" method="post">
    {% csrf_token %}
        {% for field in form %}
        <div class="form-group{% if field.errors %} is-invalid {% endif %}">
        <div class="col-md-9">
            <label for="{{ field.auto_id }}">{{ field.label }}</label>
            {% render_field field class='form-control' %}
            {% for error in field.errors %}
                <span class="invalid-feedback">{{ error }}</span>
            {% endfor %}
        </div>
        </div>
        {% endfor %}
        <button type="submit" class="btn btn-primary">Enviar</button>
    </form>
        </div>
    </div>
{% endblock %}

core/templates/index.html
{% extends "base.html" %}

{% block container %}
    <div class="row">

      <div class="col-lg-3">

        <h1 class="my-4">Django</h1>
        <div class="list-group">
            {% for categoria in categorias %}
                <a href="{{ categoria.get_absolute_url }}" class="list-group-item">{{ categoria.name }}</a>
            {% endfor %}
        </div>

      </div>
      <!-- /.col-lg-3 -->

      <div class="col-lg-9">

        <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
          <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
          </ol>
          <div class="carousel-inner" role="listbox">
            <div class="carousel-item active">
              <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="First slide">
            </div>
            <div class="carousel-item">
              <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="Second slide">
            </div>
            <div class="carousel-item">
              <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="Third slide">
            </div>
          </div>
          <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>

        <!-- /.row -->

      </div>
      <!-- /.col-lg-9 -->

    </div>
    <!-- /.row -->
{% endblock %}

core/templates/login.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block title %}
    Login | {{ block.super }}
{% endblock %}

{% block container %}
<div class="row">
      <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
        <div class="card card-signin my-5">
        {% for error in form.non_field_errors %}
                <div class="alert-danger">
                {{ error }}
                </div>
            {% endfor %}
          <div class="card-body">
            <h5 class="card-title text-center">Entrar</h5>
            <form class="form-signin" method="post">
            {% csrf_token %}
              <div class="form-label-group {% if field.username.errors %} is-invalid {% endif %}">
                    {% for error in field.errors %}
                        <span class="invalid-feedback">{{ error }}</span>
                    {% endfor %}
                {% render_field form.username class="form-control" %}
                <label for="{{ form.username.auto_id }}">{{ form.username.label }}</label>
              </div>

              <div class="form-label-group {% if field.password.errors %} is-invalid {% endif %}">
                {% render_field form.password class="form-control" %}
                <label for="{{ form.password.auto_id }}">{{ form.password.label }}</label>
              </div>

              <div class="custom-control custom-checkbox mb-3">
                <input type="checkbox" class="custom-control-input" id="customCheck1">
                <label class="custom-control-label" for="customCheck1">Recuperar senha</label>
              </div>
              <button class="btn btn-lg btn-primary btn-block text-uppercase" type="submit">Entrar</button>
              <hr class="my-4">
            </form>
          </div>
        </div>
      </div>
    </div>
{% endblock %}

core/templates/pagination.html
<div class="row">
        <div class="col-md-12">
            <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-center">
                <li class="page-item {% if not page_obj.has_previous %}disabled{% endif %}">
                    <a class="page-link" href="?page={{ page }}{{ getvars }}">Previous</a>
                </li>
                    {% for page in paginator.page_range %}
                    <li class="page-item {% if page_obj.number == page %}active{% endif %}">
                        <a class="page-link " href="?page={{ page }}{{ getvars }}">{{ page}}</a></li>
                    {% endfor %}
                    <li class="page-item {% if not page_obj.has_next %}disabled{% endif %}">
                        <a class="page-link" href="?page={{ page }}{{ getvars }}">Next</a>
                    </li>
                </li>
                </ul>
            </nav>
        </div>
    </div>

core/templates/sobre.html
{% extends "base.html" %}

{% block title %}
    Sobre | {{ block.super }}
{% endblock %}

{% block container %}
    <h1 class="my-4">Sobre</h1>
    <div class="row">
<div class="col-lg-3">
<nav id="navbar-example3" class="navbar navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <nav class="nav nav-pills flex-column">
    <a class="nav-link" href="#item-1">Item 1</a>
    <nav class="nav nav-pills flex-column">
      <a class="nav-link ml-3 my-1" href="#item-1-1">Item 1-1</a>
      <a class="nav-link ml-3 my-1" href="#item-1-2">Item 1-2</a>
    </nav>
    <a class="nav-link" href="#item-2">Item 2</a>
    <a class="nav-link" href="#item-3">Item 3</a>
    <nav class="nav nav-pills flex-column">
      <a class="nav-link ml-3 my-1" href="#item-3-1">Item 3-1</a>
      <a class="nav-link ml-3 my-1" href="#item-3-2">Item 3-2</a>
    </nav>
  </nav>
</nav>
</div>

        <div class="col-lg-9">

<div data-spy="scroll" data-target="#navbar-example3" data-offset="0">
  <h4 id="item-1">Item 1</h4>
  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas vitae nulla at tortor dignissim pharetra.
      Sed porttitor sed justo sit amet varius. Pellentesque tincidunt arcu vel nisi blandit ullamcorper.
      Morbi sed sapien lacinia, interdum augue quis, blandit mauris. Etiam a nunc id quam tempor sollicitudin.
      In hac habitasse platea dictumst. Donec rhoncus odio rutrum mi malesuada, vel pharetra ex tempor.
      Cras massa neque, molestie vitae fringilla id, tempus vel tortor.
      Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.</p>
  <h5 id="item-1-1">Item 1-1</h5>
  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas vitae nulla at tortor dignissim pharetra.
      Sed porttitor sed justo sit amet varius. Pellentesque tincidunt arcu vel nisi blandit ullamcorper.
      Morbi sed sapien lacinia, interdum augue quis, blandit mauris. Etiam a nunc id quam tempor sollicitudin.
      In hac habitasse platea dictumst. Donec rhoncus odio rutrum mi malesuada, vel pharetra ex tempor.
      Cras massa neque, molestie vitae fringilla id, tempus vel tortor.
      Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.</p>
  <h5 id="item-1-2">Item 1-2</h5>
  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas vitae nulla at tortor dignissim pharetra.
      Sed porttitor sed justo sit amet varius. Pellentesque tincidunt arcu vel nisi blandit ullamcorper.
      Morbi sed sapien lacinia, interdum augue quis, blandit mauris. Etiam a nunc id quam tempor sollicitudin.
      In hac habitasse platea dictumst. Donec rhoncus odio rutrum mi malesuada, vel pharetra ex tempor.
      Cras massa neque, molestie vitae fringilla id, tempus vel tortor.
      Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.</p>
    <h4 id="item-2">Item 2</h4>
  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas vitae nulla at tortor dignissim pharetra.
      Sed porttitor sed justo sit amet varius. Pellentesque tincidunt arcu vel nisi blandit ullamcorper.
      Morbi sed sapien lacinia, interdum augue quis, blandit mauris. Etiam a nunc id quam tempor sollicitudin.
      In hac habitasse platea dictumst. Donec rhoncus odio rutrum mi malesuada, vel pharetra ex tempor.
      Cras massa neque, molestie vitae fringilla id, tempus vel tortor.
      Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.</p>
    <h4 id="item-3">Item 3</h4>
  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas vitae nulla at tortor dignissim pharetra.
      Sed porttitor sed justo sit amet varius. Pellentesque tincidunt arcu vel nisi blandit ullamcorper.
      Morbi sed sapien lacinia, interdum augue quis, blandit mauris. Etiam a nunc id quam tempor sollicitudin.
      In hac habitasse platea dictumst. Donec rhoncus odio rutrum mi malesuada, vel pharetra ex tempor.
      Cras massa neque, molestie vitae fringilla id, tempus vel tortor.
      Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.</p>
    <h5 id="item-3-1">Item 3-1</h5>
  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas vitae nulla at tortor dignissim pharetra.
      Sed porttitor sed justo sit amet varius. Pellentesque tincidunt arcu vel nisi blandit ullamcorper.
      Morbi sed sapien lacinia, interdum augue quis, blandit mauris. Etiam a nunc id quam tempor sollicitudin.
      In hac habitasse platea dictumst. Donec rhoncus odio rutrum mi malesuada, vel pharetra ex tempor.
      Cras massa neque, molestie vitae fringilla id, tempus vel tortor.
      Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.</p>
    <h5 id="item-3-2">Item 3-2</h5>
  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas vitae nulla at tortor dignissim pharetra.
      Sed porttitor sed justo sit amet varius. Pellentesque tincidunt arcu vel nisi blandit ullamcorper.
      Morbi sed sapien lacinia, interdum augue quis, blandit mauris. Etiam a nunc id quam tempor sollicitudin.
      In hac habitasse platea dictumst. Donec rhoncus odio rutrum mi malesuada, vel pharetra ex tempor.
      Cras massa neque, molestie vitae fringilla id, tempus vel tortor.
      Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.</p>
</div>
            </div>
            </div>
{% endblock %}