accounts/urls.py
from django.urls import path

from . import views


app_name = 'accounts'
urlpatterns = [
    path('', views.minha_conta, name='minha_conta'),
    path('registro/', views.register, name='register'),
    path('atualizaUsuario/', views.atualiza_user, name='atualiza_user'),
    path('atualizaSenha/', views.atualiza_password, name='atualiza_senha')
]

catalogo/urls.py
from django.urls import path

from . import views


app_name = 'catalogo'
urlpatterns = [
    path('', views.servicos, name='servicos'),
    path('<slug:slug>/', views.categoria, name='categoria'),
    path('produtos/<slug:slug>/', views.servico, name='servico'),

]

checkout/urls.py
from django.urls import path

from . import views


app_name = 'checkout'
urlpatterns = [
    path('carrinho/adicionar/<slug:slug>/', views.create_cart_item, name='create_cart_item'),

]

djangoecommerce/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views

from core import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('login', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout', auth_views.LogoutView.as_view(next_page='/'), name='logout'),
    path('', views.index, name='index'),
    path('sobre/', views.sobre, name='sobre'),
    path('contato', views.contato, name='contato'),
    path('catalogo/', include('catalogo.urls', namespace='catalogo')),
    path('conta/', include('accounts.urls', namespace='accounts')),
    path('compras/', include('checkout.urls', namespace='checkout'))

]

catalogo/models.py
from django.db import models
from django.urls import reverse


class Categoria(models.Model):

    name = models.CharField('Nome', max_length=100)
    slug = models.SlugField('Identificador', max_length=100)

    created = models.DateTimeField('Criado em', auto_now_add=True)
    modified = models.DateTimeField('Modificado em', auto_now_add=True)

    class Meta:
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('catalogo:categoria', kwargs={'slug': self.slug})

class Servico(models.Model):

    name = models.CharField('Nome', max_length=100)
    slug = models.SlugField('Identificador', max_length=100)
    categoria = models.ForeignKey('catalogo.Categoria', on_delete=models.CASCADE)
    descricao = models.TextField('Descrição', blank=True)
    preco= models.DecimalField('Preço', decimal_places=2, max_digits=10)

    created = models.DateTimeField('Criado em', auto_now_add=True)
    modified = models.DateTimeField('Modificado em', auto_now_add=True)

    class Meta:
        verbose_name = 'Serviço'
        verbose_name_plural = 'Serviços'
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('catalogo:servico', kwargs={'slug': self.slug})

catalogo/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic

from .models import Servico, Categoria


class ServicosListView(generic.ListView):

    model = Servico
    template_name = 'catalogo/servicos.html'
    context_object_name = 'servicos'
    paginate_by = 2


servicos = ServicosListView.as_view()


class CategoriaListView(generic.ListView):

    template_name = 'catalogo/categoria.html'
    context_object_name = 'servicos'
    paginate_by = 2

    def get_queryset(self):
        return Servico.objects.filter(categoria__slug=self.kwargs['slug'])

    def get_context_data(self, **kwargs):
        context = super(CategoriaListView, self).get_context_data(**kwargs)
        context['categoria'] = get_object_or_404(Categoria, slug=self.kwargs['slug'])
        return context


categoria = CategoriaListView.as_view()


def servico(request, slug):
    context = {
        'servico': Servico.objects.get(slug=slug)
    }
    return render(request, 'catalogo/servico.html', context)

catalogo/templates/catalogo/_servico.html
<div class="col-lg-4 col-md-6 mb-4">
            <div class="card h-100">
              <a href="{{ servico.get_absolute_url }}"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
              <div class="card-body">
                <h4 class="card-title">
                  <a href="{{ servico.get_absolute_url }}">{{ servico.name }}</a>
                </h4>
                <h5>{{ servico.preco }}</h5>
                <p class="card-text">{{ servico.descricao|linebreaks }}</p>
              </div>
              <div class="card-footer">
                <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
                  <a href="{% url 'checkout:create_cart_item' servico.slug %}" class="btn btn-success">Adicionar ao carrinho</a>
              </div>
            </div>
          </div>

catalogo/templates/catalogo/categoria.html
{% extends "base.html" %}

{% block title %}
    {{ categoria }} | {{ block.super }}
{% endblock %}

{% block container %}
    <h1 class="my-4">{{ categoria }}</h1>

    <div class="row">
        {% for servico in servicos %}
            {% include 'catalogo/_servico.html' %}
        {% endfor %}

    </div>

{% endblock %}

catalogo/templates/catalogo/servico.html
{% extends "base.html" %}

{% block title %}
    {{ servico }} | {{ block.super }}
{% endblock %}

{% block container %}

      <div class="col-lg-9">

        <div class="card mt-4">
          <img class="card-img-top img-fluid" src="http://placehold.it/900x400" alt="">
          <div class="card-body">
            <h3 class="card-title">{{ servico.name }}</h3>
            <h4>{{ servico.preco }}</h4>
            <p class="card-text">{{ servico.descricao|linebreaks }}</p>
            <span class="text-warning">&#9733; &#9733; &#9733; &#9733; &#9734;</span>
            4.0 stars
              |<a href="{% url 'checkout:create_cart_item' servico.slug %}" class="btn btn-success">Adicionar ao carrinho</a>
          </div>
        </div>
        <!-- /.card -->

        <div class="card card-outline-secondary my-4">
          <div class="card-header">
            Product Reviews
          </div>
          <div class="card-body">
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis et enim aperiam inventore, similique necessitatibus neque non! Doloribus, modi sapiente laboriosam aperiam fugiat laborum. Sequi mollitia, necessitatibus quae sint natus.</p>
            <small class="text-muted">Posted by Anonymous on 3/1/17</small>
            <hr>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis et enim aperiam inventore, similique necessitatibus neque non! Doloribus, modi sapiente laboriosam aperiam fugiat laborum. Sequi mollitia, necessitatibus quae sint natus.</p>
            <small class="text-muted">Posted by Anonymous on 3/1/17</small>
            <hr>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis et enim aperiam inventore, similique necessitatibus neque non! Doloribus, modi sapiente laboriosam aperiam fugiat laborum. Sequi mollitia, necessitatibus quae sint natus.</p>
            <small class="text-muted">Posted by Anonymous on 3/1/17</small>
            <hr>
          </div>
        </div>
        <!-- /.card -->

      </div>
      <!-- /.col-lg-9 -->


{% endblock %}

catalogo/templates/catalogo/servicos.html
{% extends "base.html" %}

{% load pagination %}

{% block title %}
    Serviços | {{ block.super }}
{% endblock %}

{% block container %}
    <h1 class="my-4">Servicos</h1>
    <div class="row">
        {% for servico in servicos %}
            {% include 'catalogo/_servico.html' %}
        {% endfor %}
    </div>
    {% pagination request paginator page_obj %}
{% endblock %}